# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 20:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200, verbose_name='endereço')),
                ('bairro', models.CharField(max_length=100)),
                ('ncep', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.IntegerField(validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(9)])),
                ('telefone2', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(9)], verbose_name='telefone 2')),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('google', models.CharField(blank=True, max_length=200)),
                ('twitter', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('imagem', models.ImageField(upload_to='quem/')),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='membros/')),
                ('descricao', models.TextField(verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Quem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('imagem', models.ImageField(upload_to='quem/')),
            ],
        ),
    ]
