# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 23:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Meu contato', editable=False, max_length=10, unique=True)),
                ('endereco', models.CharField(max_length=200, verbose_name='endereço')),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Digite um CEP válido. Ex: 99999-999', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido. Ex: 99 99999-9999', regex='^\\d{2}\\s\\d{5}-\\d{4}$')])),
                ('telefone2', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido. Ex: 99 99999-9999', regex='^\\d{2}\\s\\d{5}-\\d{4}$')], verbose_name='telefone 2')),
                ('facebook', models.URLField(blank=True)),
                ('google', models.URLField(blank=True, verbose_name='Google Plus')),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Equipe', editable=False, max_length=10, unique=True)),
                ('descricao', models.TextField(max_length=400, verbose_name='descrição')),
                ('imagem', models.ImageField(upload_to='equipe/')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='galeria/%Y/%m/%d/')),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Utilize somente letras, espaços e números', regex='^(\\w+\\s?)+$')])),
                ('cargo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='membros/')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('facebook', models.URLField(blank=True)),
                ('google', models.URLField(blank=True, verbose_name='Google Plus')),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Quem somos', editable=False, max_length=10, unique=True)),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('imagem', models.ImageField(upload_to='quem/')),
            ],
        ),
    ]
