# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 21:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='ncep',
        ),
        migrations.AddField(
            model_name='contato',
            name='cep',
            field=models.CharField(default='', max_length=9, validators=[django.core.validators.RegexValidator(message='Digite um CEP válido. Ex: 99999-999', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='google',
            field=models.URLField(blank=True, verbose_name='Google Plus'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido. Ex: 99 99999-9999', regex='^\\d{2}\\s\\d{5}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone2',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido. Ex: 99 99999-9999', regex='^\\d{2}\\s\\d{5}-\\d{4}$')], verbose_name='telefone 2'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='imagem',
            field=models.ImageField(upload_to='equipe/'),
        ),
    ]
