# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_auto_20170916_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='google',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='google',
        ),
        migrations.AddField(
            model_name='contato',
            name='instagram',
            field=models.URLField(blank=True, verbose_name=b'Instagram'),
        ),
        migrations.AddField(
            model_name='membro',
            name='instagram',
            field=models.URLField(blank=True, verbose_name=b'Instagram'),
        ),
    ]
