# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 18:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_auto_20170929_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Digite um CEP válido. Ex: 99999-999', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Informe um celuar válido. Ex: 99 99999-9999', regex='^\\d{2}\\s\\d{5}-\\d{4}$')], verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone2',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido. Ex: 99 9999-9999', regex='^\\d{2}\\s\\d{4}-\\d{4}$')], verbose_name='telefone fixo'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='descricao',
            field=models.TextField(max_length=400, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='descricao',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Utilize somente letras, espaços e números', regex='^(\\w+\\s?)+$')]),
        ),
        migrations.AlterField(
            model_name='quem',
            name='descricao',
            field=models.TextField(verbose_name='descrição'),
        ),
    ]
