# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_contato_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='quem',
            name='nome',
            field=models.CharField(default='Quem somos', editable=False, max_length=10, unique=True),
        ),
    ]
