# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_auto_20171016_1606'),
        ('paginas', '0002_auto_20171002_1904'),
    ]

    operations = [
    ]
