# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 19:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_auto_20171016_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(default='Meu contato', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Informe um celular válido. Ex: 99 99999-9999', regex='^\\d{2}\\s\\d{5}-\\d{4}$')], verbose_name='celular'),
        ),
    ]
