# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_quem_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='nome',
            field=models.CharField(default='Equipe', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(default='Meu contato', editable=False, max_length=10, unique=True),
        ),
    ]
