# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_auto_20170829_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='google',
            field=models.URLField(blank=True, verbose_name='Google Plus'),
        ),
        migrations.AddField(
            model_name='membro',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
