# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_auto_20170829_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='descricao',
            field=models.TextField(max_length=400, verbose_name='descrição'),
        ),
    ]
