# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_auto_20170829_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='galeria/')),
                ('data_de_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='data de publicação')),
            ],
        ),
    ]
