# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='data_de_publicacao',
        ),
        migrations.AddField(
            model_name='foto',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
