# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 23:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_auto_20170831_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Utilize somente letras, espaços e números', regex='^(\\w+\\s?)+$')]),
        ),
    ]
