# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 23:10
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='preço')),
                ('categoria', models.CharField(max_length=100)),
                ('avaliacao', models.TextField(verbose_name='avaliação')),
                ('nota1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('nota2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('nota3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('nota4', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('imagem', models.ImageField(upload_to='cervejas/')),
                ('descricao', models.TextField(max_length=1000, verbose_name='descrição da cerveja')),
                ('data_de_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de criação')),
                ('data_de_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='data de publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Utilize somente letras, espaços e números', regex='^(\\w+\\s?)+$')])),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='preço')),
                ('local', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200, verbose_name='endereço')),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Digite um CEP válido. Ex: 99999-999', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='cursos/')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('organizador', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Utilize somente letras, espaços e números', regex='^(\\w+\\s?)+$')])),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido. Ex: 99 99999-9999', regex='^\\d{2}\\s\\d{5}-\\d{4}$')])),
                ('data_de_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de início')),
                ('duracao', models.CharField(max_length=100, verbose_name='duração')),
                ('data_de_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de criação')),
                ('data_de_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='data de publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('imagem', models.ImageField(upload_to='posts/')),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_de_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de criação')),
                ('data_de_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='data de publicação')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
