# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome do cliente'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='endereco',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
