# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170916_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerveja',
            name='familia',
            field=models.CharField(default=b'none', max_length=100, verbose_name=b'fam\xc3\xadlia'),
        ),
    ]
