# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(storage='/Users/jordy/Documents/Projetos/Acens/EscolaCervejeira-master/media', upload_to=''),
        ),
    ]
