# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 13:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170925_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerveja',
            name='data_de_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de criação'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de publicação'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='descricao',
            field=models.TextField(max_length=1000, verbose_name='avaliação da cerveja'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='estilo',
            field=models.CharField(max_length=100, verbose_name='estilo'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='imagem',
            field=models.ImageField(upload_to='cervejas/'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='nota1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='aparência'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='nota2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='aroma'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='nota3',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='sabor e corpo'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='nota4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='paladar'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(upload_to='clientes/', verbose_name='logo do cliente'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.BooleanField(default=False, verbose_name='é um evento?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
    ]
