# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171016_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(editable=False, max_length=100),
        ),
    ]
