# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170917_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultoria',
            name='imagem',
            field=models.ImageField(upload_to='consultoria/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(upload_to='eventos/'),
        ),
    ]
