# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 21:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170918_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cerveja',
            name='familia',
        ),
        migrations.AddField(
            model_name='cerveja',
            name='estilo',
            field=models.CharField(default='', max_length=100, verbose_name='estilo'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='nota1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='aparência'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='nota2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='aroma'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='nota3',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='sabor e corpo'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='nota4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='paladar'),
        ),
    ]
