# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171016_1649'),
        ('blog', '0004_auto_20171002_1904'),
    ]

    operations = [
    ]
