# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170919_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerveja',
            name='estilo',
            field=models.CharField(max_length=100, verbose_name='estilo'),
        ),
    ]
