# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170823_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='grade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
