# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170918_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parceiro',
            name='position',
        ),
    ]
