# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 00:29
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_parceiro_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='position',
            field=geoposition.fields.GeopositionField(default=b'', max_length=42),
        ),
    ]
