# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170823_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
