# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 00:30
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_parceiro_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
