# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170823_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='picture',
            field=models.ImageField(upload_to='beer/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(upload_to='course/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='post/'),
        ),
    ]
