# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170919_1844'),
        ('blog', '0011_auto_20170918_2130'),
    ]

    operations = [
    ]
