# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170823_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
