# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170920_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_de_criacao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_de_inicio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_de_publicacao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='local',
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(default='Eventos', editable=False, max_length=10, unique=True),
        ),
    ]
