# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 17:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170824_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
