# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_merge_20170920_1029'),
        ('blog', '0015_post_tag'),
    ]

    operations = [
    ]
