# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 18:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_merge_20170921_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultoria',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='data_de_criacao',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='data_de_inicio',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='data_de_publicacao',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='email',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='local',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='organizador',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='consultoria',
            name='imagem',
            field=models.ImageField(upload_to='clientes/', verbose_name='logo do cliente'),
        ),
        migrations.AlterField(
            model_name='consultoria',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Utilize somente letras, espaços e números', regex='^(\\w+\\s?)+$')], verbose_name='nome do cliente'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='position',
            field=geoposition.fields.GeopositionField(default='3.7906405,-38.6585446', max_length=42),
        ),
    ]
