# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170922_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultoria',
            new_name='Cliente',
        ),
    ]
