# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170824_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
