# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20170824_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contact',
            field=models.CharField(default='contato@escolacervejeira.com.br', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='organizer',
            field=models.CharField(default='Urlan', max_length=50),
            preserve_default=False,
        ),
    ]
