# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20170824_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='place',
            new_name='address',
        ),
        migrations.AddField(
            model_name='course',
            name='city',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
