# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170824_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='zipcode',
            field=models.CharField(default='60000-000', max_length=9),
            preserve_default=False,
        ),
    ]
