# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 20:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_course_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='place',
            field=models.CharField(default='Escola do Teste', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='zipcode',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
