# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 18:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20170824_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('categoria', models.CharField(max_length=200)),
                ('avaliacao', models.DecimalField(decimal_places=0, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('imagem', models.ImageField(upload_to='beer/')),
                ('descricao', models.TextField(max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('local', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('cidade', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='course/')),
                ('descricao', models.TextField()),
                ('organizador', models.CharField(max_length=50)),
                ('email', models.CharField(default='contato@escolacervejeira.com.br', max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Beer',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
