# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 18:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20170826_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cerveja',
            old_name='preco',
            new_name='preço',
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='avaliacao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
