# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20170826_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cerveja',
            old_name='avaliacao',
            new_name='avaliação',
        ),
        migrations.RenameField(
            model_name='cerveja',
            old_name='created_date',
            new_name='data_de_criação',
        ),
        migrations.RenameField(
            model_name='cerveja',
            old_name='published_date',
            new_name='data_de_publicação',
        ),
        migrations.RenameField(
            model_name='cerveja',
            old_name='descricao',
            new_name='descrição',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='created_date',
            new_name='data_de_criação',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='start_date',
            new_name='data_de_início',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='published_date',
            new_name='data_de_publicação',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='descricao',
            new_name='descrição',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='end_date',
            new_name='duração',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='endereco',
            new_name='endereço',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='preco',
            new_name='preço',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='data_de_publicação',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='date_de_criação',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='título',
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='imagem',
            field=models.ImageField(upload_to='cervejas/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(upload_to='cursos/'),
        ),
    ]
