# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20170826_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duração',
            field=models.IntegerField(default=0),
        ),
    ]
