# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 22:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20170826_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cerveja',
            name='avaliação',
        ),
        migrations.RemoveField(
            model_name='cerveja',
            name='data_de_criação',
        ),
        migrations.RemoveField(
            model_name='cerveja',
            name='data_de_publicação',
        ),
        migrations.RemoveField(
            model_name='cerveja',
            name='descrição',
        ),
        migrations.RemoveField(
            model_name='cerveja',
            name='preço',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='data_de_criação',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='data_de_início',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='data_de_publicação',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='descrição',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='duração',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='endereço',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='preço',
        ),
        migrations.RemoveField(
            model_name='post',
            name='data_de_publicação',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_de_criação',
        ),
        migrations.RemoveField(
            model_name='post',
            name='título',
        ),
        migrations.AddField(
            model_name='cerveja',
            name='avaliacao',
            field=models.IntegerField(db_column='avaliação', default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cerveja',
            name='data_de_criacao',
            field=models.DateTimeField(db_column='data_de_criação', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cerveja',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, db_column='data_de_publicação', null=True),
        ),
        migrations.AddField(
            model_name='cerveja',
            name='descricao',
            field=models.TextField(db_column='descrição', default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cerveja',
            name='preco',
            field=models.DecimalField(db_column='preço', decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_de_criacao',
            field=models.DateTimeField(db_column='data_de_criação', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_de_inicio',
            field=models.DateTimeField(db_column='data_de_início', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, db_column='data_de_publicação', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(db_column='descrição', default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='duracao',
            field=models.IntegerField(db_column='duração', default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='endereco',
            field=models.CharField(db_column='endereço', default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(db_column='preço', decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='post',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, db_column='data_de_publicação', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date_de_criacao',
            field=models.DateTimeField(db_column='data_de_criação', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(db_column='título', default='', max_length=200),
            preserve_default=False,
        ),
    ]
