# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20170828_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerveja',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, db_column='data_de_publicação', default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, db_column='data_de_publicação', default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, db_column='data_de_publicação', default=django.utils.timezone.now, null=True),
        ),
    ]
