# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 23:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20170828_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerveja',
            name='avaliacao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='avaliação'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='data_de_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_de_criação'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data_de_publicação'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='descricao',
            field=models.TextField(max_length=1000, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_de_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_de_criação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_de_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_de_início'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data_de_publicação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao',
            field=models.IntegerField(default=0, verbose_name='duração'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data_de_publicação'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_de_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_de_criação'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
    ]
