# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 21:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20170829_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cep',
            field=models.CharField(default='', max_length=9, validators=[django.core.validators.RegexValidator(message='Digite um CEP válido. Ex: 99999-999', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Digite um nome válido. Ex: Seu Nome De Exemplo ', regex='^([A-Z][a-zA-Z]+\\s*)+$')]),
        ),
    ]
