# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 22:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20170829_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerveja',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Digite um nome válido. Ex: Seu Nome De Exemplo ', regex='^([A-Z][a-zA-Z]+\\s*)+$')]),
        ),
    ]
