# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 23:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20170831_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='bairro',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='telefone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido. Ex: 99 99999-9999', regex='^\\d{2}\\s\\d{5}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='data_de_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de criação'),
        ),
        migrations.AlterField(
            model_name='cerveja',
            name='descricao',
            field=models.TextField(max_length=1000, verbose_name='descrição da cerveja'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_de_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de criação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao',
            field=models.CharField(max_length=100, verbose_name='duração'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_de_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de criação'),
        ),
    ]
